### ISSUE TITLE
Interactive nav getting pushed off top of screen in mobile view.

### ISSUE THREAD

**Issue by amgranger** [ny/universal-navigation#106]
## Success Criteria
- [ ] harden #nygov-universal-navigation base font-size to: font-size: 17px;  as mentioned in #113 
## Notes

Testing out interactive nav, it appears to go off to the top of the screen.

http://sitweb06-pub.otda.state.nyenet/

![image](https://cloud.githubusercontent.com/assets/8571474/4594370/0093b294-508f-11e4-9e25-2eb826c6d6b9.png)

Not seeing any overlapping styles, but this doesn't appear to happen on the demo version.  It is a critical issue for us, as our site is responsive so the static version of the banner is no longer an option (as of today, the static version isn't a great responsive option).   Any insight would be greatly appreciated.

**Comment by steve-ross** [comment]
The fix for us was to enable the search option so that container is drawn but add this class so that is not displayed:

```
/* fixes bug in nygov header when you try to turn off the search setting */

.nygov-universal_searcher {visibility: hidden;}

```

Hope that helps

**Comment by tjcrommie** [comment]
Retest with new release"

**Comment by Goldieashe** [comment]
based on a brief sampling, it doesn't appear to happen on our sites any longer. If one or two others could test we can close this issues

**Comment by amgranger** [comment]
I'm unable to reproduce the original error or subsequent reports of font size related issues.    Banner is displaying as expected.
