### ISSUE TITLE
Footer not showing up

### ISSUE THREAD

**Issue by Lukenickerson** [ny/universal-navigation#143]
Expected result:
- [ ] Footer should be displayed on every page load
- [ ] Footer should appear when using IE8
- [ ] Footer should appear when using iOS (iPhone, iPad) #150 

Test pages: 
 * http://nys-its.github.io/universal-navigation/demos/interactive-option-demo.html 
 * http://qaapps.cio.ny.gov/apps/mediacontact/public/
 * http://otda.ny.gov/
 * More links in #150

**Comment by bmtKIA6** [comment]
Unable to reproduce.
Is this still an issue?

@tjcrommie 
@lukecharde

**Comment by goodship11** [comment]
no comments since november and can't reproduce currently.
