### ISSUE TITLE
Universal Footer not displaying on iPhone or iPad

### ISSUE THREAD

**Issue by lmurdock** [ny/universal-navigation#150]
These sites are not displaying the footer on iPhone or iPad:

http://cutpropertytaxes.ny.gov/
http://licensecenter.ny.gov/
http://stormrecovery.ny.gov/community-reconstruction-program
http://stormrecovery.ny.gov/
http://www.hallofnewyork.ny.gov/
http://freshconnect.ny.gov/
http://www.justicecenter.ny.gov/
http://regionalcouncils.ny.gov/
http://www.governor.ny.gov/smart-schools-ny
http://archive.governor.ny.gov/anti-hunger-task-force
http://www.governor.ny.gov/diversity/home
http://www.governor.ny.gov/common-core-panel
http://www.governor.ny.gov/2013/new-york-rising
http://www.governor.ny.gov/EmergencyPreparednessCommissions
http://www.governor.ny.gov/puttingstudentsfirst
http://www.governor.ny.gov/anewnyprogressreport
http://www.governor.ny.gov/mandatereliefcouncil
http://www.governor.ny.gov/20122013ExecutiveBudget
http://www.governor.ny.gov/stateofthestate2011
http://www.governor.ny.gov/AdvisorVulnerablePersons
http://www.governor.ny.gov/sage
http://www.governor.ny.gov/building-a-new-NY
http://www.governor.ny.gov/peoplefirstcampaign
http://www.governor.ny.gov/stateofthestate2012

**Comment by bmtKIA6** [comment]
@lukecharde  can this issue be closed?

**Comment by goodship11** [comment]
can't reproduce and no comments since novemebter
