### ISSUE TITLE
Static uNav not displaying correctly

### ISSUE THREAD

**Issue by gingerg** [ny/universal-navigation#163]
http://dev.veterans.ny.gov/user/login
... not loading CSS at all on IE11 on and off the state network. AFAIK this is an instance issue. 

![image](https://cloud.githubusercontent.com/assets/2808099/5271140/91b75fbc-7a3f-11e4-90f9-dbc3a2bcde42.png)

![image](https://cloud.githubusercontent.com/assets/2808099/5271152/a80a34ec-7a3f-11e4-9f51-5260282382f5.png)

**Comment by bmtKIA6** [comment]
Is this still an issue?

@tjcrommie

**Comment by tjcrommie** [comment]
This is caused by   <meta http-equiv="X-UA-Compatible" content="IE=8"> and having the browser emulate a IE 8 Browser. The solution is to update you website to current standards and remove the meta tag.

**Comment by gingerg** [comment]
resolved, closing
