### ISSUE TITLE
uNav Alerts cover the Nav display on smaller screens

### ISSUE THREAD

**Issue by esteinborn** [ny/universal-navigation#170]
# Actionable Items

- [ ] uNav should not get covered by alerts on small screen sizes.

#### UPDATE: 12/12:
> It's not happening on very small now, but the first breakpoint drops down too low again.
> Looks to be coming along but needs more work

The fix looks to be adjusting the dynamic height of the iframe at specific breakpoints. (found that 407px seemed to be fine at super small screen sizes.

When resizing the unav: http://dcjs.ny.gov/nygov.htm the navigation gets covered by the content:

![image](https://cloud.githubusercontent.com/assets/308007/5363462/52926aa0-7faa-11e4-92dc-1d34ef14f7ba.png)

**Comment by lukecharde** [comment]
Is this still an issue, if only one alert is displayed at at a time?

http://ny.github.io/universal-navigation/demos/static-option-demo-DEV.html

**Comment by bmtKIA6** [comment]
Please, confirm that this is still an issue and close if everything is ok.

**Comment by goodship11** [comment]
@esteinborn @patik is this still a problem?

**Comment by esteinborn** [comment]
I can verify tomorrow

**Comment by patik** [comment]
The demo page only shows one alert currently so it's hard to say if this is fixed. Is there a way to get both yellow and red alerts to display at once?

**Comment by lukecharde** [comment]
Only one will be displayed at a time per operational practice.

**Comment by esteinborn** [comment]
That's different from what I have last heard, but if its the latest info, this isn't a problem any more. Assuming there will only ever be one alert.

**Comment by lukecharde** [comment]
Can those who posted the above screenshots above post corresponding screenshots pointing a uNav DEV (1 banner) to validate that this is no longer an issue?

**Comment by patik** [comment]
Windows Chrome:

![image](https://cloud.githubusercontent.com/assets/262137/6392950/d405f918-bd93-11e4-98c9-528e86890fab.png)

Android 4.3 (Samsung Galaxy S4)

![image](https://cloud.githubusercontent.com/assets/262137/6393005/48639ed2-bd94-11e4-8ed1-7083bc5cc398.png)


tax.ny.gov looks the same (i.e. working correctly).

**Comment by goodship11** [comment]
![image](https://cloud.githubusercontent.com/assets/1169421/6400710/f183a1f4-bdc8-11e4-8875-a176f02d5644.png)

iphone looks good

**Comment by goodship11** [comment]
with the assumption that there won't be two alerts at once, closing. thanks for the help!
