### ISSUE TITLE
uAlerts Not Opening in New Tab

### ISSUE THREAD

**Issue by robinmiller25** [ny/universal-navigation#179]
# Actionable Items:
- [ ] Alert links need to open in a new tab/window

## Problem:
With new window param set:
1. Nav links open in new tab/window
2. Alert links do NOT open in a new tab/window

In the original banner, we had the option of opening the banner links in a new window, but there doesn't seems to be a way to do that with the two new additional areas.

**Comment by bmtKIA6** [comment]
Is this still an issue. 

Please, verify and if the issue still occurs, provide a dev/qa link if possible


cc
@lukecharde 
@tjcrommie

**Comment by lukecharde** [comment]
Closing, appears that @robinmiller25 just needed the guidance for how to do it.
