### ISSUE TITLE
NYS image is scrunched on small screens

### ISSUE THREAD

**Issue by patik** [ny/universal-navigation#189]
Affects iOS 8.1, latest desktop Chrome, probably others.

http://ny.github.io/universal-navigation/demos/static-option-demo.html

iPhone 5S:

![image](https://cloud.githubusercontent.com/assets/262137/5881142/44aa88d4-a30c-11e4-868d-f6b5e2a455d1.png)

Latest desktop Chrome:

![image](https://cloud.githubusercontent.com/assets/262137/5881138/3a3d9dd2-a30c-11e4-8f7a-ecc78451afd0.png)

**Comment by CourtneyJordan** [comment]
This issue can be fixed by removing the images inline styles for width and height and setting the img logo height: auto inside the css.

The inline styles on the img element are causing the logo to crush.

**Comment by bmtKIA6** [comment]
Unable to reproduce.

Please, verify.


@tjcrommie

**Comment by CourtneyJordan** [comment]
This issue was occurring when the blizzard of 2015 alert was out. I recently checked some impacted sites and the issue is no longer occurring. @patik can you verify if the issue has been resolved?

**Comment by patik** [comment]
Everything is tiny now. But I guess the original issue (stretched/incorrect aspect ratio) is resolved.

![image](https://cloud.githubusercontent.com/assets/262137/6381245/9af0f32a-bd0d-11e4-95bb-4f169b4895ed.png)

**Comment by tjcrommie** [comment]
Please retest with new release @patik

**Comment by patik** [comment]
Looks fine now.
