### ISSUE TITLE
Interactive Navigation caused script conflicts

### ISSUE THREAD

**Issue by BrianMiller86** [ny/universal-navigation#190]
With redesign and update of the Open Budget site (http://openbudget.ny.gov/), we were asked to try using the Interactive Universal Navigation instead of the Static Navigation.

That changed caused performance of the "forms" pages (especially "Budget & Actuals" and "School Aid") to fail in IE9, according to the Application Developer, although they appeared to work as expected in IE11.

Switching back to the Static Navigation completely resolved the issue.

**Comment by lukecharde** [comment]
Thanks @BrianMiller86 

Good call.

Can you post links to the pages in question so it can be considered the next time there is an iteration of the universal navigation?  Any thoughts on where the conflict was or how to remedy?  Instance issue/conflict or globally fixable?

**Comment by tjcrommie** [comment]
@BrianMiller86 please retest with new release.

**Comment by BrianMiller86** [comment]
Ran tests with interactive and static universal navigation.

We no longer see the performance failure in IE8 or IE9, although the application take slightly longer to load data the data set with the interactive navigation in place.
