### ISSUE TITLE
uNav Alert problem with secure site for testing

### ISSUE THREAD

**Issue by judy-akers** [ny/universal-navigation#196]
While attempting to test how the uNav Alert would look on our main public site, the Alert section will not work because our test site is https://.  It generates a message that "This connection is untrusted..." (firefox) or "Content was blocked because it was not signed by a valid security certificate." (IE).

Is there a version of the TEST code (where it points to src="//nygovdev.prod.acquia-sites.com/load_global_menu/ajax?iframe=true" data-updated="2014-11-07 08:30") that does have a security certificate so that I can test this before rolling it out to production?

You can see this at https://beta.hesc.ny.gov/

**Comment by lukecharde** [comment]
You will need to add the security exception for testing against NY.GOV Dev.
