### ISSUE TITLE
Code to test the Alerts has disappeared again. 

### ISSUE THREAD

**Issue by judy-akers** [ny/universal-navigation#198]
How can I test the Alerts code when it keeps being removed from src="//static-assets.ny.gov/load_global_menu/ajax?iframe=true" data-updated="2014-11-07 08:30"?

Is there another URL I should use until I get my template with a fixed menu issue resolved?

**Comment by Goldieashe** [comment]
http://nys-its.github.io/universal-navigation/demos/interactive-option-demo-DEV.html doesn't have the test alert up currently

**Comment by lukecharde** [comment]
Once the test alert is put back up, instructions for testing against NY.GOV DEV are at https://github.com/nys-its/universal-navigation/blob/gh-pages/notes/testing-against-development-staging.md

**Comment by bmtKIA6** [comment]
The emergency alert was pushed to the dev environment.

http://nygovdev.prod.acquia-sites.com/

**Comment by judy-akers** [comment]
Thank You! That is a big help so I can figure out how to get our fixed top bar menu to temporarily shift for an Alert.

Now to brush up on my javascript skills – or bribe the resident javascript guru to help me.

**Comment by angli-socrata** [comment]
Is the emergency alert still on the dev environment? I have followed https://github.com/ny/universal-navigation/blob/gh-pages/notes/testing-against-development-staging.md#static-header to load the static header, but no alert is showing up.
