### ISSUE TITLE
Static banner links are awkwardly aligned on small screens

### ISSUE THREAD

**Issue by patik** [ny/universal-navigation#204]
The links are never quite vertically aligned on screens below ~670px. The screen shots below are from the [static dev demo](http://ny.github.io/universal-navigation/demos/static-option-demo-DEV.html) on Chrome. 

Note how the links jump to the bottom at around 500px.

![image](https://cloud.githubusercontent.com/assets/262137/7499275/891e02fa-f3f4-11e4-9dd9-1eb257ed34f3.png)

![image](https://cloud.githubusercontent.com/assets/262137/7499284/91714138-f3f4-11e4-98cb-e48b4bef2ae5.png)

![image](https://cloud.githubusercontent.com/assets/262137/7499279/8ca5d98e-f3f4-11e4-9a28-1780c9008b44.png)

![image](https://cloud.githubusercontent.com/assets/262137/7499281/8eafb27c-f3f4-11e4-853a-d3fe7824e94c.png)

**Comment by tjcrommie** [comment]
Looks like this is corrected, please test. @patik

**Comment by patik** [comment]
Much better
