### ISSUE TITLE
Fluidity of the NYS logo makes it hard to align with page content

### ISSUE THREAD

**Issue by patik** [ny/universal-navigation#205]
I wanted to bring up a potential design issue since the web guidelines are presumably being developed at this time. This isn't a bug in the uNav or even a criticism.

Given the placement, large size, and prominent visual design of the uNav banner it's reasonable that a site may want to align with it. For example, a site may want to use padding around the body that matches the padding used in the banner, or perhaps a lockup needs to be aligned with the NYS logo.

However, the NYS logo shifts around based on the width of the page. Note how the red line intersects with the page content at different points, and that the purple lines (which represent the padding/indentation of the logo image) change in length:

![image](https://cloud.githubusercontent.com/assets/262137/7499577/ab1f6220-f3f6-11e4-8b13-99acc94616b4.png)

![image](https://cloud.githubusercontent.com/assets/262137/7499579/adc444a0-f3f6-11e4-9bd3-059c3546e0c9.png)

![image](https://cloud.githubusercontent.com/assets/262137/7499581/b0ae5ca0-f3f6-11e4-9f34-5aec104faabf.png)

Of course some movement is expected and necessary in a responsive design. But <abbr title="if and only if">iff</abbr> the web guidelines call for page content to be aligned with the banner this would need to be addressed in some way. For example, perhaps the logo "section" could have a fixed width (changing at certain breakpoints) while the rest of the banner remained flexible.

**Comment by mfarfanr** [comment]
:+1:

**Comment by tjcrommie** [comment]
Closing the guidelines do not call for it to align with the content.

**Comment by esteinborn** [comment]
I agree with Patik that at a design level, not having the content align with the unav. If the official guidelines for the unav and style guide do not contain considerations for aligning the width of the site content with the unav, there should be a discussion on that. It doesn't look right unaligned.
Closing this issue in this repo may make sense, but having a discussion about the issue in the official style guide repo is necessary.
