### ISSUE TITLE
Dynamic search results in May '15 unav release have inconsistent behavior

### ISSUE THREAD

**Issue by Goldieashe** [ny/universal-navigation#206]
Steps to recreate (screenshots below):
- (1) Type search term in "search" box, allow it to dynamically suggest terms/phrases.
- (2) Select one - unav extends down to show results.
- (3) Click the "x" to close the drop down of results.
- (4) Type term in search box again - it doesn't dynamically suggest terms/phrases. (this is different from current production interactive unavs - they do show suggestions at this point)

I'm not sure of the criticality of this issue - since you can click through to the search results by clicking "submit." I mostly wanted to document the inconsistency.

Sites that the new (dev) unav has been tried on:
-	http://dev.vietnamgallery.ogs.ny.gov/user
-	http://dev.combatheroin.ny.gov/user
-	http://dev.regionalcouncils.ny.gov/user

1. 
![image](https://cloud.githubusercontent.com/assets/2806467/7504521/ecbbd458-f418-11e4-8f33-81f7995fcbde.png)

2. 
![image](https://cloud.githubusercontent.com/assets/2806467/7504529/fc609876-f418-11e4-88f8-517b02fbd8b9.png)

3. 
![image](https://cloud.githubusercontent.com/assets/2806467/7504539/1720d612-f419-11e4-8fd9-0698afc5dbaf.png)

4. 
![image](https://cloud.githubusercontent.com/assets/2806467/7504545/2d275f94-f419-11e4-8daf-e5fc29541d52.png)

**Comment by amgranger** [comment]
Additionally, wasn't this originally meant to only search the current site and then give the option to search all of ny.gov?

**Comment by tjcrommie** [comment]
This has been resolved.
