### ISSUE TITLE
Dev version of Interactive Banner Shows "Recommended Search Results" when 'Local' is clicked.

### ISSUE THREAD

**Issue by amgranger** [ny/universal-navigation#207]
![image](https://cloud.githubusercontent.com/assets/8571474/7519111/2fa3a568-f4ad-11e4-851f-fe7acac13d4d.png)

Fairly self-explanatory.  When Local is clicked, expands with 'Recommended Search Results'.

**Comment by tjcrommie** [comment]
@amgranger  Amanda Clear your cache and ctrl F5 refresh. We can not duplicate it and I have seen this before on my system but it was fixed once I cleared my cache. Please let us know the results.
Tim

**Comment by amgranger** [comment]
Clearing the cache resolved it.  Should I close this?

**Comment by Goldieashe** [comment]
Hi @amgranger - I'll close it, but if you discover more issues around it, please feel free to re-open.
