### ISSUE TITLE
Uncaught Type Error $(...).dotdotdot is not a function

### ISSUE THREAD

**Issue by amgranger** [ny/universal-navigation#208]
global-nav-bundle.js  line: 378

To reproduce: 

Go to Settings -> Location.   

Reproduced on governor.ny.gov, otda.ny.gov, opwdd.ny.gov.

**Comment by Goldieashe** [comment]
We've noticed that this seems to happen on sites which have multiple msg:
 "You have included the Google Maps API multiple times on this page. This may cause unexpected errors."

This doesn't happen on every site with this revised interactive nav - I wonder if it's related to how the google map api *possibly* interferes with other functions when called more than once

If you do a view source on governor.ny.gov 
<script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script> is called on line 51 and line 85

Possibly related "Google Maps API called in interactive uNav can conflict with local Google Map implementations" #155

**Comment by tjcrommie** [comment]
Please verify this has been corrected.

**Comment by Goldieashe** [comment]
http://www.governor.ny.gov/ no longer throws this error - with retesting by @amgranger  - if the fix is confirmed we can close.

**Comment by amgranger** [comment]
Confirmed fixed.
