### ISSUE TITLE
Fonts (especially Proxima Nova) not displaying in Google Chrome versions

### ISSUE THREAD

**Issue by BrianMiller86** [ny/universal-navigation#220]
Rebranding-related fonts (Proxima Nova) are not displaying In "older" versions of Google Chrome (reported for version 47.0.2526.106 m and 43.0.2357.124 m (the latter is 64-bit on Windows 7 home premium}.  

Numerous comments have been submitted to DTF (via the online survey for taxpayers) about this issue in the last several days, such as the following:

"... site is useless on a desktop computer. I'm using Google Chrome v. 43.0.2357.124 m (64-bit) on Windows 7 home premium on the desktop and the pages have NO content. I see just the page framework, but there's no text. The drop-down lists on the left open up when clicked, but there's no text, just white rectangles."

"... I can't see anything on the screen using Google Chrome. I had to install Internet Explorer in order to send this message. I reported this problem several times and nothing has been done to correct it. Are you saying that you don't support the most popular browser in the world, or simply won't correct a problem even though it is tax season and you are preventing people from using the site? That's amazing."

**Comment by BrianMiller86** [comment]
Screen capture showing the issue:

![tax - chrome_anon](https://cloud.githubusercontent.com/assets/8866907/14610785/3ee8fa98-055d-11e6-9a78-89b3a38913ca.jpg)

**Comment by BrianMiller86** [comment]
Appears solved for Tax site.  Fonts that were first deployed last year were replaced by newer versions in more recent zips from this site.

**Comment by mfarfanr** [comment]
Brian,

Did we reach out to the taxpayer after you replaced the fonts? I would like to know if reloading the page (make sure cache gets cleared on his end) solves his issue since it looks like a combination of `old font files` and some `environment-specific variables`.

**Comment by BrianMiller86** [comment]
Not to my knowledge.  Matt O'Brien was able to reproduce the issue with an older laptop, and the fix was confirmed there.  The information was presented to the OCPA web team last week (5/4)

**Comment by mfarfanr** [comment]
Ok Thanks.
