### ISSUE TITLE
Output version/build info for assets

### ISSUE THREAD

**Issue by Lukenickerson** [ny/universal-navigation#38]
To aid in testing could we get a version number output to the console or as an HTML comment to let us know we're looking at a new version of the banner / footer?

The current interactive banner -- http://nys-its.github.io/universal-navigation/demos/interactive-option-demo.html -- just had similar JavaScript errors to #15 , but they seem to be gone when I last refreshed. I assume new versions of the banner are being pushed out during the day while testing is happening. It is not clear to testers whether there are encountering intermittent issues or things are being patched. 

![image](https://cloud.githubusercontent.com/assets/3942453/4476853/6cdc93c0-4979-11e4-8989-6964774f343d.png)

**Comment by tjcrommie** [comment]
Las test UNav release has version number
