### ISSUE TITLE
Clarify "Where should this be deployed" guidance

### ISSUE THREAD

**Issue by esteinborn** [ny/universal-navigation#47]
https://github.com/nys-its/universal-navigation/blob/gh-pages/notes/faqs.md#where-should-the-universal-navigation-be-deployed

Add more clarification around these items:

**Not required:**
The audience is NYS employees

**Required:**
The audience is citizens/business.
Any public facing websites/apps regardless of login requirement.

**Comment by goodship11** [comment]
Policy should provide clarity. If still needed we can reopen a new issue.
