### ISSUE TITLE
News and Government links go to content on static nav that is different than interactive nav

### ISSUE THREAD

**Issue by Lukenickerson** [ny/universal-navigation#59]
On interactive site, News link loads general news and Government link loads three branches of government. On static site, News goes to governor's press releases (http://governor.ny.gov/news) and Government goes to governor's site (http://governor.ny.gov). Unsure whether this is intended or an oversight.

Suggestions for production:
* News =  http://news.ny.gov or http://ny.gov/news/ (doesn't exist yet)
* Government = http://ny.gov/services/government or http://ny.gov/government (doesn't exist yet) that could showcase the three branches, similar to interactive menu for Government

Split issue from #39

**Comment by tjcrommie** [comment]
The new interactive nav links to the same pages as the static....
