### ISSUE TITLE
IE 8 Static Nav Styles are affecting page styles

### ISSUE THREAD

**Issue by tjcrommie** [ny/universal-navigation#65]
## Success Criteria
- [ ] item

## Notes

In IE 8 we are experiencing a strange style issue, When the page loads styles are adopting the Static Nav styles. Sometimes the page styles will over right the Nav Styles and the page returns to its desired state. Other times the pages styles do not over write the NAV styles and the page is left with the wrong display, See attached Screen Shots, This seems to only happen in IE 8
![devissue](https://cloud.githubusercontent.com/assets/5625155/4542456/c2274102-4e21-11e4-824e-3c7c3297ed89.png)
![pth-style-issue](https://cloud.githubusercontent.com/assets/5625155/4542457/c3faab04-4e21-11e4-9456-44c33573baf0.png)
![pth-style-issue2](https://cloud.githubusercontent.com/assets/5625155/4542458/c6dcc5a0-4e21-11e4-88de-1e14643fda87.png)

**Comment by tjcrommie** [comment]
Closing no longer supporting ie 8 at the DOT

**Comment by patik** [comment]
Was this actually fixed? Judging by @Lukenickerson's comment there were other sites with this issue.

**Comment by tjcrommie** [comment]
If other sites are identified and thier IE8 analytics show enough usage to warrant action, we can reopen.
