### ISSUE TITLE
Narrow width window in IE8 does not trigger responsive navigation

### ISSUE THREAD

**Issue by Lukenickerson** [ny/universal-navigation#84]
Responsive styling is not working on the uNav w/ IE8. When using IE8 and the browser window is not open wide, the search overlaps other links, and opening any of the content (Services/News/Government) is narrow and illegible.

![image](https://cloud.githubusercontent.com/assets/3942453/4565975/73d7aa38-4f24-11e4-801d-4468491032b8.png)

**Comment by tjcrommie** [comment]
Closing unav does not does not expand anymore.
