### ISSUE TITLE
Shockwave Flash Required?

### ISSUE THREAD

**Issue by BrianMiller86** [ny/universal-navigation#89]
## Success Criteria
- [ ] item

## Notes

Finally adding this to github issues (sorry Luke); one for the  "icebox," I'm sure ...

![nygov_static_swf](https://cloud.githubusercontent.com/assets/8866907/4568813/63757768-4f3f-11e4-97d8-c15696daa48d.JPG)

Still getting indications that Shockwave Flash is invoked somewhere from both Static and Interactive Versions; only seen in specific browser (Chrome) on VDI that does not have Flash plugin.

**Comment by tjcrommie** [comment]
Retest with new version.

**Comment by BrianMiller86** [comment]
Will need the Chrome/DOB Web VDI issue to be resolved before I can test this.  The version of Chrome provided in the DOB Web VDI will no longer launch, and a different version cannot be downloaded because the Chrome installer page is blocked by ITS ("Not allowed to browse Shareware download category").  An ITSM Ticket (INC0994502) about this issue with Chrome was first submitted on 6/17/2015 (when it first stopped launching).

**Comment by BrianMiller86** [comment]
Chrome access has been restored, and this bug is no longer seen with either the static or interactive navigation.  This can be closed!
